FROM nginx

RUN apt-get update && apt-get install -y subversion
RUN rm -rf /usr/share/nginx/html/* 
ENV LANG C.UTF-8
RUN svn checkout https://github.com/trhepiernas-hub/Erronka1/trunk/WebOrria /usr/share/nginx/html
