version: '3.1'
services:
  odoo:
    image: odoo
    ports:
      - 8069:8069
    volumes:
      - odoo-data:/var/lib/odoo
    depends_on:
      - db
    container_name: odoo
  db:
    image: postgres:15
    restart: always
    volumes:
      - odooDB:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    container_name: db
  weborria:
    image: nginx
    build: https://github.com/trhepiernas-hub/Erronka1.git#main
    restart: always
    ports:
      - 8080:80
    volumes:
      - ngixn-data:/usr/share/nginx/html:ro
    container_name: WebOrria
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - CLI_ARGS= #optional
    volumes:
      - duplicati-backups:/backups
      - duplicati-source:/source
    ports:
      - 8200:8200
    restart: unless-stopped
volumes:
  ngixn-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Erronka/container/web
  odoo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Erronka/container/odoo-data
  odooDB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Erronka/container/odooDB
  duplicati-backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Erronka/duplicati/backups
  duplicati-source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:/Erronka/container