FROM lscr.io/linuxserver/duplicati:latest

RUN apt update && apt install -y subversion
RUN curl -L -o /bin/sh https://raw.githubusercontent.com/trhepiernas-hub/Erronka1/main/start.sh
CMD [ "/bin/sh", "start.sh" ]
